produce 20 // Number of hands to generate, kept low just for this example
west1n = 
	hcp(west) >= 13 && 
	hcp(west) <= 15 && 
	shape(west, any 4333 + any 4432 + any 4441 + 2335 + 2353 + 1345 + 3154 + 2254 + 2245 + 1264 + 1246 + 1336 + 3163 + 0436 + 4063 + 1156 + 1516 + 1174 + 4117)
eastRflannery = 
	hcp(east) >= 6 && 
	(hearts(east) >= 4 && spades(east) >= 5) ||
	(hearts(east) >= 5 && spades(east) >= 4)
condition west1n && eastRflannery
action printew
